- hosts: ubuntu
  gather_facts: no
  become: true
  remote_user: luiz
  tasks:
  - name: send a message to chat in playbook
    telegram:
       token: 
       chat_id:
       msg: Ansible task finished
