- hosts: orangepi
  gather_facts: no
  become: true
  remote_user: luiz
  vars_files: 
    - /home/luiz/secret/telegram.yml
  tasks:
  - name: send a message to chat in playbook
    telegram:
       token: "{{ my_token }}"
       chat_id: "{{  my_chat_id }}"
       msg: Ansible test msg
